### ISSUE TITLE
Cleanup-rules not perfect.. filtering out GOOD rules

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat-utils#1]
This trac ticket #649 was transferred from trac to github:

date: 2015-08-04
reporter: minga
ticket body:
" Cleanup-rules is filtering out some rules oclhashcat thinks are valid.

For example:
$0 $0 $0 $0 $0 $0 $0 (length 20)

It is rejected because it is too long - but in reality, it shrinks to:
$0$0$0$0$0$0$0 which is 14 chars - and DOES work.

---

some other examples:

$ $0 $3 (append SPACE 0 3)

Notice there are TWO spaces after the first dollar sign. I think this is the
root cause of all the rules that were rejected, but are still valid.

More double spaces:

o8 ]
o8 *01
o8 } *10
o8 *23
o8 $4
o8 ,4 -9
o8 ,5
o8 +6
o8 ] o1e
o8 o6n
o8 o72 Z1
o8 r x32
o8 srR
o8 Y2
o8 y3
o8 Z1 o72

+0 +0 +0 +0 +0 +0 +0 +0 (too long)
$1 $2 $3 $4 $! $@ $# $$ (too long)

Someone's rule generate space-seperates all rules - which is causing the problem."

This ticket was accepted by "atom" on the trac ticketing system.

I think there must be a bug that counts even each and every space (instead of just the rules).
Thx

**Comment by jsteube** [comment]
Ther merge fixes the issue, thanks!
