### ISSUE TITLE
cap2hccapx does not work on Big Endian systems

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat-utils#24]
Tested on a big endian MIPS router. cap2hccapx succeeds in finding the handshake on x86 but not on MIPS. Guessing due to different endianness.

**Comment by neheb** [comment]
ran clang-analyzer. It complains on line 492. Error is:

Pointer arithmetic on non-array variables relies on memory layout, which is dangerous.

**Comment by jsteube** [comment]
Support was added with commit: https://github.com/hashcat/hashcat-utils/commit/6b02370a8f87b761a492da49e7908c5fcdc0876c

Please try and close the issue if it's working on your system.
