### ISSUE TITLE
cap2hccapx - priority to get correct essid and essid_len

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat-utils#27]
cap2hccapx evaluates the beacon and the proberesponse to get the essid and essid_len. That's not enough:
On hidden ssid's, mailformed packets, and/or packet loss of proberesponse  cap2hccapx fails to get the necessary essid.
It's a better way to get essid and essid_len from reassociationrequest or associationrequest which are sent immediately before the eapol sequence.
cap2hccapx should use the following priority (from high to low) te get essid and essid_len:
1. re-associationrequest
2. associationrequest
3. proberesponse
4. directed proberequest (proberequest to mac_ap - not to BROADCAST)
5. beacon

Best regards
ZerBea

**Comment by jsteube** [comment]
Should be implemented with commit https://github.com/hashcat/hashcat-utils/commit/a926258623a9f47be88bffb8824c2b3aebc64f9d

Please test. If it's not working, please reopen the ticket
