### ISSUE TITLE
macOs how to run?

### ISSUE THREAD

**Issue by vipheyue** [hashcat/hashcat-utils#35]
macOs how to run?

**Comment by jsteube** [comment]
Just compile from source. Doesn't work?

**Comment by vipheyue** [comment]
compile the source then generate xxxx.bin   .. this this i can't exec

**Comment by jsteube** [comment]
I don't understand what's the problem. Please rephrase

**Comment by mineo210** [comment]
@vipheyue first compile it: "gcc -o cap2hccapx cap2hccapx.c" and then run it: "./cap2hccapx"

**Comment by davut5** [comment]
mkdir -p ${HOME}/.local/share/hashcat

**Comment by davut5** [comment]
first 

brew install hashcat;

**Comment by vipheyue** [comment]
您好，您发送的邮件我已经收到。我查阅后,会尽快回复您！

**Comment by matrix** [comment]
check here #41

**Comment by vipheyue** [comment]
您好，您发送的邮件我已经收到。我查阅后,会尽快回复您！
