### ISSUE TITLE
pull request for makefile for mac?

### ISSUE THREAD

**Issue by resistor4u** [hashcat/hashcat-utils#37]
If I `git clone https://github.com/hashcat/hashcat-utils.git && cd hashcat-utils/src/ && make` on my mac, it appears the default Makefile setup does not correctly move the *.bin files to the ./bin folder. I've tried editing the Makefile to fix this on a fork I made of this repo, and it was successful for me. I edited Makefile line7 from
`all: clean`
to
`all: clean native`
`	mv *.bin ../bin`
`	cp -a *.pl ../bin`
This worked for me. But I'm only just a learner in these matters, and I expect that my edits are probably not the best solution. If what I've done is a solution, should I submit a pull request for this? Otherwise, could you please advise how to correct this behavior on macs?

Ideally, I'd like to see this repo in homebrew. But I've had a very, very difficult time creating my own formula for this, and I suspect it's because the Makefile behavior here is not working. So, first things first.

**Comment by jsteube** [comment]
I can't say anything on this as I myself do not have access to a macOS system. If you send in a PR, please make sure it does not break any existing Linux compilation process. I'll merge it then.
