### ISSUE TITLE
unable to 'make'

### ISSUE THREAD

**Issue by CaseyKevin** [hashcat/hashcat-utils#40]
When I run make it just removes all the files in bin and stops. I tried just compiling cap2haccapx.c manually but it's still not working.

(I'm fairly new to linux)

**Comment by jsteube** [comment]
please ask on forum

**Comment by hook-s3c** [comment]
Not really helpful for the rest of us. Please update your documentation and test it.

**Comment by hook-s3c** [comment]
```
cd hashcat-utils/src

make

cp *.bin ../bin
```
