### ISSUE TITLE
cap2hccapx: What does it require to detect networks?

### ISSUE THREAD

**Issue by a11ce** [hashcat/hashcat-utils#46]
I have a pcap containing only handshakes (using Wireshark's eapol display filter). When run with this file as input, cap2hccapx prints "Networks detected: 0" and writes nothing. When run with the exact same capture session but no filter (all the packets captured during the session, no eapol filter) it works as expected. What packets other than the handshake does cap2hccapx require to detect networks? And, if you happen to know, what Wireshark filter will include these?

**Comment by jsteube** [comment]
Please ask on hashcat forum.
