### ISSUE TITLE
"Written 0 WPA Handshakes to ..."

### ISSUE THREAD

**Issue by PunkmeisterDuy** [hashcat/hashcat-utils#55]
When I try to convert some .pcap files, I am unable to get any WPA handshakes I obtained using Pwnagotchi. For some networks it does, but for most of them it says 0 WPA handshakes. Is it because they're not using the WPA standard and I am using the wrong utility. I have been using the cap2hccapx.exe command.

**Comment by SammCheese** [comment]
Its because the file doesnt contain a Handshake, not an issue with cap2hccapx
