### ISSUE TITLE
Link to documentation in README

### ISSUE THREAD

**Issue by Wingman4l7** [hashcat/hashcat-utils#57]
Replace "tbd" in the Description section with a link to the wiki: https://hashcat.net/wiki/doku.php?id=hashcat_utils

**Comment by xxkryptos** [comment]
This might be a good start for now, but I'm not a big fan of linking external resources in git repositories. Perhaps the documentation could be brought in to the main repository and reflected on the site? I'm not certain the website uses markdown which would could require an effort to port the documentation.
