### ISSUE TITLE
Failed to run file

### ISSUE THREAD

**Issue by iMonZ** [hashcat/hashcat-utils#59]
Error:

Failed to execute process 'cap2hccapx.exe'. Reason:
exec: Exec format error
The file 'cap2hccapx.exe' is marked as an executable but could not be run.

**Comment by xxkryptos** [comment]
Are you running this from Linux or WSL? `exec: Exec format error` looks like an error you might see on Linux. It appears that you are trying to run the Windows binary (`cap2hccapx.exe`). You need to be running the *Linux* binary if you are in fact using Linux.

Try heading over to the `hashcat-utils`[ releases page](https://github.com/hashcat/hashcat-utils/releases) and downloading the latest release. You are going to want the latest release. Make sure you download the `.7z` file, avoid the files that say `source code` next to them. Extract the files and run `./cap2hccapx.bin`. You may need to make the file executable first with `chmod +x ./cap2hccapx.bin`.

If this fails, there are online services that allow you to convert cap to hccapx online. I would recommend searching `cap to hccapx hashcat`. Obviously, it would not be wise to upload anything too sensitive to one of these services. In any case, please report back. It will help in determining if there is a bug in the code that needs to be fixed.

Hope that helps!

**Comment by Xanadrel** [comment]
Closing because it's been a while, and @xxkryptoshas given a good answer.
Feel free to reopen/comment if there is an actual problem.
